export const FETCH_PRODUCTS = 'FETCH_PROCUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const FILTER_PRODUCTS_BY_SIZE = 'FILTER_PRODUCTS_BY_SIZE';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';